
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

USE `HospitalManagement`;


insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (1, 'Dita', 'Charke', 'Janitor', '645-829-8189', 12);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (2, 'Noach', 'Birbeck', 'Therapist', '586-523-6412', 7);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (3, 'Lezlie', 'Johncey', 'Radiologist', '606-306-4439', 6);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (4, 'Anya', 'Rixon', 'Clerk', '323-191-6321', 1);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (5, 'Neill', 'Ringwood', 'Pharmacist', '467-596-5601', 4);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (6, 'Elsy', 'Smithies', 'Radiologist', '847-174-4003', 12);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (7, 'Aidan', 'Chapelle', 'Security Guard', '141-702-0431', 9);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (8, 'Thacher', 'Trimnell', 'Technician', '917-457-7188', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (9, 'Ally', 'Pinches', 'Surgeon', '365-972-4837', 1);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (10, 'Ana', 'Boden', 'Nurse', '992-370-5889', 4);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (11, 'Tiphany', 'Boustred', 'Administrator', '418-252-8526', 9);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (12, 'Lucienne', 'Mapam', 'Surgeon', '855-573-4567', 3);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (13, 'Gael', 'Bras', 'Technician', '615-287-6584', 1);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (14, 'Clarice', 'Skeeles', 'Administrator', '585-737-4528', 7);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (15, 'Drucie', 'Bortolini', 'Technician', '176-660-7362', 1);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (16, 'Marchelle', 'Kenson', 'Surgeon', '765-994-7149', 8);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (17, 'Concettina', 'Haken', 'Radiologist', '524-232-1527', 11);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (18, 'Emmerich', 'Munns', 'Nurse', '644-707-9077', 5);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (19, 'Ricardo', 'Winston', 'Receptionist', '742-461-5571', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (20, 'Geneva', 'Wimmers', 'Pharmacist', '996-786-6844', 4);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (21, 'Lindsay', 'Cardenas', 'Security Guard', '972-386-3541', 7);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (22, 'Reagen', 'Vidgen', 'Security Guard', '227-651-5748', 1);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (23, 'Frasco', 'Meegin', 'Receptionist', '449-745-9542', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (24, 'Aile', 'Valsler', 'Security Guard', '197-555-0878', 10);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (25, 'Callida', 'Carleton', 'Janitor', '662-236-4024', 12);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (26, 'Herschel', 'Grossier', 'Radiologist', '621-116-8138', 4);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (27, 'Gar', 'Aberchirder', 'Surgeon', '817-772-1250', 9);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (28, 'Kakalina', 'Scone', 'Technician', '772-441-8857', 3);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (29, 'Lin', 'Bedells', 'Doctor', '197-575-4170', 9);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (30, 'Riane', 'Brewin', 'Clerk', '156-265-5312', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (31, 'Constancia', 'Arthars', 'Pharmacist', '700-411-6615', 9);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (32, 'Ezra', 'Jump', 'Technician', '780-589-4575', 4);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (33, 'Ash', 'Girtin', 'Radiologist', '485-760-9683', 10);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (34, 'Brinn', 'Gurton', 'Technician', '937-630-7513', 7);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (35, 'Grady', 'Earl', 'Pharmacist', '866-552-0136', 6);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (36, 'Rodney', 'Cluett', 'Pharmacist', '851-570-2773', 3);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (37, 'Kele', 'Grise', 'Technician', '339-777-8346', 5);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (38, 'Wally', 'Focke', 'Surgeon', '179-523-1432', 1);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (39, 'Lorinda', 'Bellefant', 'Janitor', '462-699-2653', 11);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (40, 'Vincent', 'Brunini', 'Clerk', '855-359-8359', 4);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (41, 'Wes', 'Staunton', 'Therapist', '560-107-8126', 7);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (42, 'Lorita', 'Keady', 'Therapist', '177-593-2630', 8);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (43, 'Wendell', 'Jannaway', 'Pharmacist', '516-879-1392', 7);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (44, 'Nelli', 'Ashmore', 'Therapist', '394-399-5018', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (45, 'Ansley', 'Heads', 'Surgeon', '905-570-8853', 6);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (46, 'Rosene', 'Langthorn', 'Clerk', '873-105-5611', 6);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (47, 'Shell', 'Saket', 'Pharmacist', '679-126-7547', 6);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (48, 'Amalle', 'Ast', 'Technician', '220-300-0179', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (49, 'Ailsun', 'Feacham', 'Therapist', '197-715-9546', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (50, 'Lenna', 'Coverdale', 'Receptionist', '393-883-9267', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (51, 'Ronny', 'Andell', 'Radiologist', '293-778-0833', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (52, 'Eberhard', 'Coan', 'Technician', '160-842-0360', 6);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (53, 'Millisent', 'Barns', 'Janitor', '470-945-8753', 8);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (54, 'Guglielmo', 'Tilio', 'Therapist', '812-572-6646', 8);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (55, 'Farrel', 'Kubczak', 'Administrator', '231-145-6254', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (56, 'Ruddy', 'Bowick', 'Janitor', '587-579-8292', 2);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (57, 'Odelinda', 'Fishpond', 'Radiologist', '738-344-1963', 12);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (58, 'Marcelle', 'Gwatkin', 'Technician', '334-186-7219', 10);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (59, 'Chev', 'Spohr', 'Security Guard', '645-981-0332', 8);
insert into Faculty (employeeID, firstName, lastName, role, tel_number, department) values (60, 'Sal', 'Irwin', 'Nurse', '785-466-0251', 9);
