insert into Item (itemID, itemName) values (1, 'Stethoscope');
insert into Item (itemID, itemName) values (2, 'Blood pressure cuff');
insert into Item (itemID, itemName) values (3, 'Thermometer');
insert into Item (itemID, itemName) values (4, 'Surgical gloves');
insert into Item (itemID, itemName) values (5, 'Syringes');
insert into Item (itemID, itemName) values (6, 'Needles');
insert into Item (itemID, itemName) values (7, 'IV catheters');
insert into Item (itemID, itemName) values (8, 'Bandages');
insert into Item (itemID, itemName) values (9, 'Gauze pads');
insert into Item (itemID, itemName) values (10, 'Surgical masks');
insert into Item (itemID, itemName) values (11, 'Alcohol swabs');
insert into Item (itemID, itemName) values (12, 'Antiseptic solution');
insert into Item (itemID, itemName) values (13, 'Sutures');
insert into Item (itemID, itemName) values (14, 'Scalpels');
insert into Item (itemID, itemName) values (15, 'Medical tape');
insert into Item (itemID, itemName) values (16, 'Electrocardiogram (ECG) machine');
insert into Item (itemID, itemName) values (17, 'X-ray machine');
insert into Item (itemID, itemName) values (18, 'MRI machine');
insert into Item (itemID, itemName) values (19, 'Ultrasound machine');
insert into Item (itemID, itemName) values (20, 'Defibrillator');
