
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

USE `HospitalManagement`;

insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (1, 'Valencia', 'Bauser', 'Female', '623-730-7161', 'vbauser0@woothemes.com', null,1 );
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (2, 'Eolanda', 'Compford', 'Female', '324-432-0913', 'ecompford1@thetimes.co.uk', null, 2);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (3, 'Tamara', 'Niessen', 'Female', '676-612-9516', 'tniessen2@adobe.com', null, 3);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (4, 'Noll', 'Claisse', 'Male', '145-740-0963', 'nclaisse3@nih.gov', null, 4);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (5, 'Timmy', 'Fletcher', 'Male', '564-467-5776', 'tfletcher4@tumblr.com', null, 5);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (6, 'Valentin', 'Nan Carrow', 'Male', '931-529-4575', 'vnancarrow5@nationalgeographic.com', null, 6);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (7, 'Ruddy', 'Filpi', 'Male', '495-290-2819', 'rfilpi6@blog.com', null, 7);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (8, 'Carroll', 'Rodbourne', 'Male', '110-328-3366', 'crodbourne7@webmd.com', null, 8);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (9, 'Jodie', 'Louthe', 'Male', '813-800-0324', 'jlouthe8@statcounter.com', null, 9);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (10, 'Aldrich', 'Hedon', 'Male', '520-351-8467', 'ahedon9@wp.com', null, 10);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (11, 'Risa', 'Piborn', 'Female', '407-820-5446', 'rpiborna@digg.com', null, 11);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (12, 'Kathryn', 'Hacaud', 'Female', '785-546-9638', 'khacaudb@senate.gov', null, 12);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (13, 'Mathew', 'Blaase', 'Male', '313-595-5401', 'mblaasec@princeton.edu', null, 13);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (14, 'Dexter', 'Bedinham', 'Male', '159-970-8320', 'dbedinhamd@slashdot.org', null, 14);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (15, 'Catherina', 'Koppke', 'Non-binary', '340-167-2088', 'ckoppkee@facebook.com', null, 15);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (16, 'Trueman', 'Dymoke', 'Male', '647-517-7202', 'tdymokef@hatena.ne.jp', null, 16);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (17, 'Roy', 'Lago', 'Male', '199-667-5004', 'rlagog@netlog.com', null, 17);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (18, 'Ashlin', 'Kelloch', 'Male', '640-318-6290', 'akellochh@toplist.cz', null, 18);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (19, 'Hakeem', 'Visco', 'Male', '481-553-0893', 'hviscoi@ucsd.edu', null, 19);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (20, 'Myrna', 'Mordie', 'Female', '425-726-2116', 'mmordiej@illinois.edu', null, 20);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (21, 'Germayne', 'Adam', 'Male', '591-340-2162', 'gadamk@paypal.com', null, 21);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (22, 'Michelina', 'Smylie', 'Genderqueer', '234-595-5282', 'msmyliel@facebook.com', null, 22);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (23, 'Roland', 'Yakuntsov', 'Male', '941-378-5649', 'ryakuntsovm@phpbb.com', null, 23);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (24, 'Nikkie', 'Mibourne', 'Female', '751-771-1477', 'nmibournen@delicious.com', null, 24);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (25, 'Linn', 'Fern', 'Male', '629-316-9875', 'lferno@hibu.com', null, 25);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (26, 'Waring', 'Cumine', 'Male', '830-601-1643', 'wcuminep@hatena.ne.jp', null, 26);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (27, 'Jeddy', 'Rahlof', 'Male', '261-652-0632', 'jrahlofq@narod.ru', null, 27);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (28, 'Oliviero', 'Denziloe', 'Male', '192-297-8565', 'odenziloer@washingtonpost.com', null, 28);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (29, 'Randell', 'Ruhben', 'Male', '911-233-6100', 'rruhbens@artisteer.com', null, 29);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (30, 'Darcy', 'Lepope', 'Female', '681-106-1295', 'dlepopet@timesonline.co.uk', null, 30);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (31, 'Raymund', 'Norton', 'Male', '896-545-8885', 'rnortonu@weebly.com', null, 31);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (32, 'Rahel', 'Lantiff', 'Female', '300-901-4525', 'rlantiffv@omniture.com', null, 32);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (33, 'Lion', 'Duckett', 'Male', '231-658-9959', 'lduckettw@google.es', null, 33);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (34, 'Zitella', 'Colnett', 'Female', '812-115-7878', 'zcolnettx@nature.com', null, 34);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (35, 'Neala', 'Hutchin', 'Female', '557-165-5671', 'nhutchiny@ca.gov', null, 35);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (36, 'Meredith', 'Averall', 'Male', '106-752-5686', 'maverallz@independent.co.uk', null, 36);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (37, 'Crissy', 'Masters', 'Female', '958-146-3800', 'cmasters10@hao123.com', null, 37);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (38, 'Xaviera', 'Nurden', 'Female', '373-562-8635', 'xnurden11@hugedomains.com', null, 38);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (39, 'Riobard', 'Bunt', 'Male', '933-548-5244', 'rbunt12@elegantthemes.com', null, 39);
insert into Patient (patientID, first_name, last_name, gender, tel_number, email, insurance, emergencyContact) values (40, 'Rhodia', 'Coalbran', 'Female', '753-395-5156', 'rcoalbran13@ameblo.jp', null, 40);
